account_id = "food_blogger"
name = "food_blogger"
site = "https://foodblogger.com"
keywords = [ "healthy", "organic", "plant-based",]
tone = "enthusiastic"
hashtags = []
template_id = "recipe"
status = "active"

[social_handles]
instagram = ""
pinterest = ""

[api_credentials]
pinterest_access_token = "fake_token_123"
pinterest_board_name = "Healthy Recipes"
default_image_url = "https://example.com/organic-food.jpg"
