account_id = "quick_meals"
name = "quick_meals"
template_id = "recipe"
site = "https://quickmeals.com"
keywords = [ "fast", "easy",]
tone = "neutral"
hashtags = [ "#quick", "#easyrecipes",]
outputs = []
post_queue = []
log_entries = []

[social_handles]
instagram = ""
pinterest = ""
