account_id = "quick_meals"
name = "quick_meals"
template_id = "recipe"
site = "https://quickmeals.example.com"
tone = "friendly"
status = "active"
keywords = ["fast", "easy", "weeknight"]
hashtags = ["#quickmeals", "#easyrecipes"]

outputs = []
post_queue = []
log_entries = []

[social_handles]
instagram = "@quickmeals"
pinterest = "quickmeals"
