id = "recipe_pinterest"
name = "Pinterest Recipe Pin"
description = "Generates Pinterest-optimized descriptions for recipe pins"
temperature = 0.7
model = "gpt-3.5-turbo"

[schedule]
frequency = "daily"
time = "10:00"
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
timezone = "America/New_York"
max_post_per_day = 2